"use client";
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {TeamState,day,sports} from '@/lib/team';
export type Kind='players'|'evaluations'|'trainings'|'meals'|'events'|'payments'|'contracts'|'team';
export const labels:Record<Kind,string>={players:'atleta',evaluations:'avaliação',trainings:'treino',meals:'refeição',events:'evento',payments:'mensalidade',contracts:'contrato',team:'time'};
export function Editor({kind,item,data,onClose,onSave,busy,saveError}:{kind:Kind,item?:any,data:TeamState,onClose:()=>void,onSave:(item:any)=>Promise<boolean>,busy:boolean,saveError:string}){
const defaults:Record<Kind,any>={players:{name:'',number:1,position:'',status:'Disponível'},evaluations:{playerId:data.players[0]?.id||'',date:day(),technical:8,tactical:8,physical:8,discipline:8,notes:''},trainings:{title:'',date:day(),time:'18:00',duration:60,intensity:'Moderada',athletes:[],description:'',completed:[]},meals:{title:'',time:'12:00',athletes:[],description:'',notes:''},events:{title:'',date:day(),time:'18:00',location:'',type:'Treino',opponent:'',description:'',confirmed:[]},payments:{playerId:data.players[0]?.id||'',amount:150,due:day(),status:'Pendente',paidDate:''},contracts:{playerId:data.players[0]?.id||'',start:day(),end:day(180),notes:''},team:data.team};
const [draft,setDraft]=useState<any>(item||defaults[kind]);const [error,setError]=useState('');const set=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
function input(k:string,label:string,type='text',required=true,min?:number,max?:number){return <label className="field" key={k}><span>{label}</span><input name={k} type={type} required={required} min={min} max={max} step={type==='number'?(kind==='payments'?'.01':kind==='evaluations'?'.1':'1'):undefined} value={draft[k]??''} onChange={e=>set(k,type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/></label>}
function select(k:string,label:string,options:{value:string,label:string}[]|string[]){return <label className="field" key={k}><span>{label}</span><select value={draft[k]} required onChange={e=>set(k,e.target.value)}>{options.map(o=>typeof o==='string'?<option key={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
const athlete=()=>select('playerId','Atleta',data.players.map(p=>({value:p.id,label:`${p.name} · #${p.number}`})));
const area=(k:string,label:string)=><label className="field"><span>{label}</span><textarea rows={4} maxLength={5000} value={draft[k]||''} onChange={e=>set(k,e.target.value)}/></label>;
const audience=()=> <fieldset className="audience"><legend>Destinatários</legend><label><input type="checkbox" checked={draft.athletes.length===0} onChange={e=>set('athletes',e.target.checked?[]:data.players.map(p=>p.id))}/> Todo o time</label><div className="checkgrid">{data.players.filter(p=>p.status!=='Inativo').map(p=><label key={p.id}><input type="checkbox" checked={draft.athletes.includes(p.id)} onChange={e=>set('athletes',e.target.checked?[...draft.athletes,p.id]:draft.athletes.filter((id:string)=>id!==p.id))}/>{p.name}</label>)}</div><small>Sem seleção individual, todos os atletas recebem.</small></fieldset>;
async function submit(e:React.FormEvent){e.preventDefault();setError('');if(kind==='contracts'&&draft.end<draft.start){setError('O término deve ser posterior ao início.');return;}if(kind==='players'&&(!Number.isInteger(draft.number)||data.players.some(p=>p.id!==item?.id&&p.number===draft.number))){setError('Use um número inteiro de camisa que esteja disponível.');return;}const result={...draft,...(kind!=='team'?{id:item?.id||crypto.randomUUID()}:{})};if(kind==='payments')result.paidDate=draft.status==='Pago'?(draft.paidDate||day()):'';await onSave(result);}
return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="editor" aria-describedby="editor-description"><DialogTitle>{kind==='team'?'Configurações do time':`${item?'Editar':'Adicionar'} ${labels[kind]}`}</DialogTitle><DialogDescription id="editor-description">{kind==='team'?'Personalize a identidade e a modalidade do seu time.':'Preencha os detalhes e salve para atualizar o time.'}</DialogDescription><form onSubmit={submit}>
{kind==='players'&&<>{input('name','Nome do atleta')}<div className="formgrid">{input('number','Número da camisa','number',true,0,99)}{input('position','Posição / função')}</div>{select('status','Disponibilidade',['Disponível','Em recuperação','Inativo'])}</>}
{kind==='evaluations'&&<>{athlete()}{input('date','Data da avaliação','date')}<div className="ratinginputs">{[['technical','Técnica'],['tactical','Tática'],['physical','Físico'],['discipline','Disciplina']].map(([k,l])=>input(k,`${l} · 0 a 10`,'number',true,0,10))}</div>{area('notes','Feedback do treinador')}</>}
{kind==='trainings'&&<>{input('title','Nome do treino')}<div className="formgrid">{input('date','Data','date')}{input('time','Horário','time')}{input('duration','Duração em minutos','number',true,5,480)}{select('intensity','Intensidade',['Leve','Moderada','Alta'])}</div>{area('description','Exercícios e orientações')}{audience()}</>}
{kind==='meals'&&<><div className="formgrid">{input('title','Refeição')}{input('time','Horário','time')}</div>{area('description','Alimentos e porções')}{area('notes','Orientações e substituições')}{audience()}</>}
{kind==='events'&&<>{input('title','Nome do evento')}<div className="formgrid">{select('type','Tipo',['Treino','Campeonato','Jogo amistoso','Reunião','Outro'])}{input('date','Data','date')}{input('time','Horário','time')}{input('location','Local')}</div>{['Campeonato','Jogo amistoso'].includes(draft.type)&&input('opponent','Adversário')}{area('description','Detalhes')}</>}
{kind==='payments'&&<><div className="notice">Controle de recebimentos. Este registro não realiza cobranças nem movimenta dinheiro.</div>{athlete()}<div className="formgrid">{input('amount','Valor (R$)','number',true,0,1000000)}{input('due','Vencimento','date')}{select('status','Situação',['Pendente','Pago'])}{draft.status==='Pago'&&input('paidDate','Data do recebimento','date',false)}</div></>}
{kind==='contracts'&&<>{athlete()}<div className="formgrid">{input('start','Início do vínculo','date')}{input('end','Término do vínculo','date')}</div>{area('notes','Observações do vínculo')}</>}
{kind==='team'&&<>{input('name','Nome do time')}{input('coach','Nome do treinador')}<div className="formgrid">{select('sport','Esporte',[...sports])}{input('season','Temporada')}</div>{select('financeMode','Modelo do time',['Mensalidades','Contratos'])}<div className="notice">A modalidade adapta a quadra e as posições. As escalações ficam salvas separadamente por jogo e esporte.</div></>}
{(error||saveError)&&<p role="alert" className="formerror">{error||saveError}</p>}<div className="formfooter"><Button type="button" variant="outline" onClick={onClose} disabled={busy}>Cancelar</Button><Button className="primary" type="submit" disabled={busy}>{busy?'Salvando…':'Salvar alterações'}</Button></div></form></DialogContent></Dialog>}

